
/**:
  ros__parameters:
    render: true
    scene_id: 5
    pub_port: 10253
    sub_port: 10254
    render_instance: 0
    drone:
      pose: [0.0, 0.0, 0.0, 0.0]
      cam:
        pose: [0.0, 0.0, -0.3]
        orientation: [-0.4, 1.57079632679489661923, 0.0]
